const vocabularyData = [
  {
    "id": 1,
    "level": "Level 1",
    "word": "ABANDON",
    "pron": "অ্যাব্যান্ডান",
    "meaning": "পরিত্যাগ করা।",
    "syn": "desert, relinquish, abdicate, discard, give up, forsake, quit, reject, renounce, shun",
    "ant": "retain, embrace, adopt, espouse, continue, pursue, uphold",
    "exam": "EMBA Oct, 2012; RU 2009; CU 2010-11",
    "done": false
  },
  {
    "id": 2,
    "level": "Level 1",
    "word": "ABATE",
    "pron": "অ্যাবেইট",
    "meaning": "প্রশমিত হওয়া; তীব্রতা কমে যাওয়া।",
    "syn": "subside, allay, decline, relieve, diminish, soothe, lessen, dwindle, reduce, decrease, mitigate",
    "ant": "intensify, boost, magnify, amplify, prolong, exacerbate, aggravate, exasperate",
    "exam": "অগ্রণী ব্যাংক: 2011",
    "done": false
  },
  {
    "id": 3,
    "level": "Level 1",
    "word": "ABDICATE",
    "pron": "এ্যাবৃডিকেইট",
    "meaning": "(পদ / সিংহাসন) ত্যাগ করা; (দায়িত্ব / কর্তব্য) পালন না করে পরিত্যাগ করা।",
    "syn": "shirk, relinquish, abandon, disclaim, disavow",
    "ant": "hold, seize, usurp",
    "exam": "EMBA: 2012",
    "done": false
  },
  {
    "id": 4,
    "level": "Level 1",
    "word": "ABERRATION",
    "pron": "অ্যাবে-রেই-শন",
    "meaning": "(সঠিক নিয়ম / পদ্ধতি থেকে) বিচ্যুতি; (সচরাচর ঘটে না এমন) অস্বাভাবিক ঘটনা।",
    "syn": "divergence, deviation, abnormal, queer, anomalous",
    "ant": "conformity, normal, compliance",
    "exam": "কম্বাইন্ড ৫ ব্যাংক: 2019; প্রবাসী কল্যাণ ব্যাংক: 2019; PSC: 99",
    "done": false
  },
  {
    "id": 5,
    "level": "Level 1",
    "word": "ABHOR",
    "pron": "আহোর্",
    "meaning": "তাচ্ছিল্যভরে অত্যন্ত ঘৃণা করা।",
    "syn": "loathe, detest, despise, hate, criticise, execrate, abominate, disdain, belittle",
    "ant": "desire, relish, cherish, praise, admire",
    "exam": "DU, C unit: 2011-12",
    "done": false
  },
  {
    "id": 6,
    "level": "Level 1",
    "word": "ABLE",
    "pron": "এইব্‌ল্",
    "meaning": "(১) সক্ষম, (২) দক্ষ।",
    "syn": "skilled, capable, competent, qualified, fit, adept, dexterous, dexterity, expert",
    "ant": "incapable, inept, clumsy",
    "exam": "Rupali Bank: 2011; 10 BCS; রাবি (ঘ) ২০০৯-১০",
    "done": false
  },
  {
    "id": 7,
    "level": "Level 1",
    "word": "ABOLISH",
    "pron": "অ্যা-ব-লিশ",
    "meaning": "শেষ করা; বর্জন করা; উচেছদ করা।",
    "syn": "terminate, annul, eliminate, exterminate, rescind, abrogate, repeal",
    "ant": "fabricate, forge, erect",
    "exam": "Exim ব্যাংক: 18; DU, C: 2008",
    "done": false
  },
  {
    "id": 8,
    "level": "Level 1",
    "word": "ABORTIVE",
    "pron": "অ্যাবোটি",
    "meaning": "নিষ্ফল / ব্যর্থ",
    "syn": "futile, vain, sterile, barren, debacle, unsuccessful",
    "ant": "fertile, fruitful, productive, successful",
    "exam": "DU, C unit: 2010-11",
    "done": false
  },
  {
    "id": 9,
    "level": "Level 1",
    "word": "ABRIDGE",
    "pron": "অ্যাব্রিজ",
    "meaning": "সংক্ষেপ করা",
    "syn": "condense, compress, shorten, abbreviate",
    "ant": "augment, enlarge, amplify, expand",
    "exam": "ICB নিয়োগ পরীক্ষা, 2017; Bank Job: 2009",
    "done": false
  },
  {
    "id": 10,
    "level": "Level 1",
    "word": "ABSTINENT",
    "pron": "অ্যাস্টিনেন্ট",
    "meaning": "সংযমী; কোনো খাদ্য বা পানীয় থেকে বিরত থাকা, বা কোনো কাজ পরিহার করা।",
    "syn": "abstentious, moderate, sober",
    "ant": "indulgent, permissive, intemperate, voluptuous, licentious, epicurean, sybaritical",
    "exam": "NTRCA - 2019",
    "done": false
  },
  {
    "id": 11,
    "level": "Level 1",
    "word": "ABSTRACT",
    "pron": "অ্যাবস্-ট্র্যাক্ট",
    "meaning": "(১) প্রয়োগের ক্ষেত্রে বা বাস্তবে নয়, শুধু মতবাদ বা তত্ত্ব হিসেবে; (২) বিমূর্ত = নৈর্ব্যক্তিক (৩) সারাংশ (৪) কোথাও থেকে কিছু সরানো",
    "syn": "conceptual, figurative, gist, withdraw, extract, elicit",
    "ant": "concrete, realistic, verbiage, insert",
    "exam": "DU: 2000-01",
    "done": false
  },
  {
    "id": 12,
    "level": "Level 1",
    "word": "ACCLAIM",
    "pron": "অ্যাক্লেইম্",
    "meaning": "(১) প্রশংসা করা = to praise publicly & enthusiastically (২) প্রশংসা।",
    "syn": "applaud, honor, applause, approval",
    "ant": "rebuke, denunciation, stricture, condemnation",
    "exam": "বাংলাদেশ ব্যাংক: 18; জনতা ব্যাংক: 2017",
    "done": false
  },
  {
    "id": 13,
    "level": "Level 1",
    "word": "ACCOST",
    "pron": "অ্যাকষ্ট",
    "meaning": "অপরিচিতের সঙ্গে গায়ে পড়ে আলাপ করা।",
    "syn": "encounter, address, confront, greet",
    "ant": "evade, avoid, shun, elude, withdraw",
    "exam": "DU, C: 1996-97",
    "done": false
  },
  {
    "id": 14,
    "level": "Level 1",
    "word": "ACQUIESCE",
    "pron": "অ্যাকুইয়েস্",
    "meaning": "কোনো কিছু বিনা প্রতিবাদে, নীরবে মেনে নেয়া; মৌনতার মাধ্যমে সম্মতি দেয়া।",
    "syn": "comply, assent, agree, accede, accept",
    "ant": "resist, disavow, disagree, repudiate, argue, oppose",
    "exam": "Pubali ব্যাংক: 2019",
    "done": false
  },
  {
    "id": 15,
    "level": "Level 1",
    "word": "ACUMEN",
    "pron": "অ্যাকিউমেন",
    "meaning": "তীক্ষ্ম বুদ্ধি।",
    "syn": "insight, shrewdness, sagacity, astuteness, perspicacity, discernment, penetration, agility",
    "ant": "ignorance, unawareness, shallowness",
    "exam": "RU: 2016-17",
    "done": false
  },
  {
    "id": 16,
    "level": "Level 1",
    "word": "ADAPT",
    "pron": "অ্যাডাপ্",
    "meaning": "খাপ খাওয়ানো, মানিয়ে নেয়া।",
    "syn": "adjust, conform, tailor, habituate, modify, accustom, suit, readjust",
    "ant": "misfit, clash",
    "exam": "উত্তরা ব্যাংক CO, 2017",
    "done": false
  },
  {
    "id": 17,
    "level": "Level 1",
    "word": "BARREN",
    "pron": "ব্যারেন",
    "meaning": "অনুর্বর: বন্ধ্যা: নিষ্ফল।",
    "syn": "Infertile, Sterile, Unproductive, Arid, Impotent",
    "ant": "Productive, Fertile, Fecund",
    "exam": "Level 1 Category",
    "done": false
  },
  {
    "id": 18,
    "level": "Level 1",
    "word": "BENEFACTOR",
    "pron": "বেনেফ্যাক্টর",
    "meaning": "উপকারক: দাতা",
    "syn": "Patron, Donor, Contributor",
    "ant": "Malefactor, Persecutor",
    "exam": "Level 1 Category",
    "done": false
  },
  {
    "id": 19,
    "level": "Level 1",
    "word": "BENEFICIAL",
    "pron": "বেনেফিশিয়াল",
    "meaning": "উপকারী",
    "syn": "Useful, Advantageous, Benign",
    "ant": "Useless, Harmful, Malignant",
    "exam": "RU: 2016; শিপিং: 2019; NTRCA: 2019",
    "done": false
  },
  {
    "id": 20,
    "level": "Level 1",
    "word": "BENEVOLENT",
    "pron": "বেনেভোলেন্ট",
    "meaning": "দয়ালু: সদাশয়",
    "syn": "Unselfish, Kind, Merciful",
    "ant": "Cruel, Selfish, Greedy, Malicious",
    "exam": "Level 1 Category",
    "done": false
  },
  {
    "id": 21,
    "level": "Level 1",
    "word": "BLAME",
    "pron": "ব্লেইম্",
    "meaning": "দোষ দেয়া।",
    "syn": "criticize, censure",
    "ant": "praise, admire, commend",
    "exam": "BBA: 2017",
    "done": false
  },
  {
    "id": 22,
    "level": "Level 1",
    "word": "BLAMEWORTHY",
    "pron": "ব্লেইওয়ারদি",
    "meaning": "নিন্দনীয়; দূষণীয়।",
    "syn": "responsible, reprehensible",
    "ant": "spotless, immaculate, innocent",
    "exam": "BAPEX: 16",
    "done": false
  },
  {
    "id": 23,
    "level": "Level 1",
    "word": "BOAST",
    "pron": "বোস্ট",
    "meaning": "দম্ভ করা; অহংকার করা।",
    "syn": "show off, brag, pride",
    "ant": "modesty, humility",
    "exam": "DU, C: 2020; JU: 14",
    "done": false
  },
  {
    "id": 24,
    "level": "Level 1",
    "word": "BOUNTY",
    "pron": "বাউন্টি",
    "meaning": "পুরস্কার; উদার দানশীলতা।",
    "syn": "reward, prize, gift, generosity",
    "ant": "penalty, miserliness, avarice",
    "exam": "27th BCS; ইবি, B: 2020",
    "done": false
  },
  {
    "id": 25,
    "level": "Level 1",
    "word": "BONA-FIDE",
    "pron": "বোনা-ফাইড",
    "meaning": "খাঁটি; প্রকৃত।",
    "syn": "genuine, authentic",
    "ant": "bogus, counterfeit",
    "exam": "38th BCS",
    "done": false
  },
  {
    "id": 26,
    "level": "Level 1",
    "word": "BRIEF",
    "pron": "ব্রীফ",
    "meaning": "সংক্ষিপ্ত; ক্ষণস্থায়ী।",
    "syn": "short",
    "ant": "lengthy, verbosity, prolonged",
    "exam": "",
    "done": false
  },
  {
    "id": 27,
    "level": "Level 1",
    "word": "BRUTAL",
    "pron": "ব্রুট্যাল্",
    "meaning": "নিষ্ঠুর; পাশবিক।",
    "syn": "cruel, inhuman",
    "ant": "soft-hearted, kind, merciful",
    "exam": "",
    "done": false
  },
  {
    "id": 28,
    "level": "Level 1",
    "word": "CANDOR",
    "pron": "ক্যান্ডর",
    "meaning": "অকপটতা; সরলতা।",
    "syn": "frankness, sincerity, openness",
    "ant": "diplomacy, dishonesty, hypocrisy",
    "exam": "BRUR: 18; 14th Teacher Reg",
    "done": false
  },
  {
    "id": 29,
    "level": "Level 1",
    "word": "CAPABLE",
    "pron": "কেইপাব্‌ল",
    "meaning": "যোগ্য; সক্ষম।",
    "syn": "adept, able, adroit, expert, competent",
    "ant": "inept, unskilled, incompetent, incapable",
    "exam": "MBBS: 2019-20",
    "done": false
  },
  {
    "id": 30,
    "level": "Level 1",
    "word": "CARELESS",
    "pron": "কেয়ারলেস্",
    "meaning": "অসতর্ক।",
    "syn": "negligent, incautious, insincere",
    "ant": "prudent, attentive, aware",
    "exam": "",
    "done": false
  },
  {
    "id": 31,
    "level": "Level 1",
    "word": "CAUTIOUS",
    "pron": "কশাস্",
    "meaning": "সতর্ক; সতর্কতাপূর্ণ।",
    "syn": "circumspect, vigilant, alert, discreet",
    "ant": "rash, reckless, careless",
    "exam": "DU, D: 19-20; JU: 14",
    "done": false
  },
  {
    "id": 32,
    "level": "Level 1",
    "word": "CHAOS",
    "pron": "ক্যাওস্",
    "meaning": "বিশৃঙ্খলা।",
    "syn": "disorder, mess, anarchy",
    "ant": "order, harmony",
    "exam": "RU: 15; RU: 14",
    "done": false
  },
  {
    "id": 33,
    "level": "Level 1",
    "word": "CHARITABLE",
    "pron": "চ্যারিট্যাবল্",
    "meaning": "দানশীল; সদয়; ক্ষমাশীল।",
    "syn": "munificent, generous, liberal, humane, beneficent",
    "ant": "miserly, parsimonious, stingy, unkind, merciless",
    "exam": "BRUR: 16; KU: 2019; NTRCA: 2019",
    "done": false
  },
  {
    "id": 34,
    "level": "Level 1",
    "word": "COALESCE",
    "pron": "কোয়ালেস্",
    "meaning": "একীভূত হওয়া।",
    "syn": "unify, unite, amalgamate, merge, integrate, combine",
    "ant": "separate, divide, segment, split, segregate",
    "exam": "মধুমতি ব্যাংক: 2017",
    "done": false
  },
  {
    "id": 35,
    "level": "Level 1",
    "word": "COMPULSORY",
    "pron": "কাম্পালসরি",
    "meaning": "বাধ্যতামূলক।",
    "syn": "mandatory, obligatory, requisite",
    "ant": "voluntary, optional",
    "exam": "BSC 6 B: 2019; NSI: 19",
    "done": false
  },
  {
    "id": 36,
    "level": "Level 1",
    "word": "CONCEAL",
    "pron": "কনসীল্",
    "meaning": "লুকাইয়া রাখা; গুপ্ত রাখা।",
    "syn": "hide, cover, submerge, disguise, camouflage",
    "ant": "reveal, disclose, unearth",
    "exam": "সোনালী ব্যাংক: 2019",
    "done": false
  },
  {
    "id": 37,
    "level": "Level 1",
    "word": "CONSTRUCTIVE",
    "pron": "কনস্ট্রাকটিভ",
    "meaning": "গঠনমূলক।",
    "syn": "beneficial, wholesome, productive, conducive",
    "ant": "destructive, useless, worthless",
    "exam": "JU: 16",
    "done": false
  },
  {
    "id": 38,
    "level": "Level 1",
    "word": "CONTAMINATE",
    "pron": "কনট্যামিনেট",
    "meaning": "দূষিত করা।",
    "syn": "adulterate, pollute, spoil, muddy",
    "ant": "purify, rinse, decontaminate",
    "exam": "",
    "done": false
  },
  {
    "id": 39,
    "level": "Level 1",
    "word": "CONTRADICT",
    "pron": "কনট্র্যাডিক্ট",
    "meaning": "বিরুদ্ধে বলা; যুক্তি খণ্ডন করা।",
    "syn": "refute, dispute, contravene, negate",
    "ant": "corroborate, confirm, affirm, support",
    "exam": "মাদক অধিদপ্তর: 2019; GRE",
    "done": false
  },
  {
    "id": 40,
    "level": "Level 1",
    "word": "CONVICT",
    "pron": "কনভিক্ট",
    "meaning": "দোষী বলে রায় দেয়া।",
    "syn": "find guilty, sentence, punish, condemn",
    "ant": "acquit, exonerate, absolve, exculpate",
    "exam": "Home মিনিস্ট্রি: 2019",
    "done": false
  },
  {
    "id": 41,
    "level": "Level 1",
    "word": "COUNTERFEIT",
    "pron": "কাউনটারফীট",
    "meaning": "জাল; কৃত্রিম।",
    "syn": "fake, bogus, mendacious, pirated",
    "ant": "genuine, real, authentic",
    "exam": "কৃষি মন্ত্রণালয়: 19",
    "done": false
  },
  {
    "id": 42,
    "level": "Level 1",
    "word": "CRISIS",
    "pron": "ক্রাইসিস",
    "meaning": "সঙ্কটকাল; চরম উদ্বেগপূর্ণ পরিস্থিতি।",
    "syn": "climax, critical situation, dilemma, deadlock",
    "ant": "blessing, calm",
    "exam": "Non cadre: 2019; সোনালী ব্যাংক: 2019",
    "done": false
  },
  {
    "id": 43,
    "level": "Level 1",
    "word": "CRUEL",
    "pron": "ক্রুয়েল",
    "meaning": "নিষ্ঠুর; নৃশংস।",
    "syn": "brutal, ruthless, callous, savage",
    "ant": "benevolent, humane, kind, compassionate",
    "exam": "প্রবাসী কল্যাণ: 2018; MBM: 16",
    "done": false
  },
  {
    "id": 44,
    "level": "Level 1",
    "word": "CYNICAL",
    "pron": "সিনিকেল",
    "meaning": "নৈরাশ্যবাদীর আচরণসম্পন্ন; স্বার্থপর।",
    "syn": "pessimistic, skeptical, distrustful",
    "ant": "optimistic, trustful, cheerful",
    "exam": "32nd BCS Preli",
    "done": false
  },
  {
    "id": 45,
    "level": "Level 1",
    "word": "DELIBERATE",
    "pron": "ডেলিবারেট",
    "meaning": "সুচিন্তিত; স্বোচ্ছাকৃত।",
    "syn": "preplanned, calculated",
    "ant": "rash, hurried, unconscious",
    "exam": "প্রা.সহ.শি. নিয়োগ: 18; BWDB: 2019",
    "done": false
  },
  {
    "id": 46,
    "level": "Level 1",
    "word": "DENY",
    "pron": "ডিনাই",
    "meaning": "অস্বীকার করা।",
    "syn": "refute, gainsay, renounce",
    "ant": "confirm, affirm, concede",
    "exam": "NSI: 2019",
    "done": false
  },
  {
    "id": 47,
    "level": "Level 1",
    "word": "DETER",
    "pron": "ডিটার",
    "meaning": "নিবৃত্ত করা; বাধা দেয়া।",
    "syn": "obstruct, discourage, prohibit, prevent",
    "ant": "assist, aid, persuade, encourage",
    "exam": "BBS: 2020",
    "done": false
  },
  {
    "id": 48,
    "level": "Level 1",
    "word": "DIMINISH",
    "pron": "ডিমিনিশ্",
    "meaning": "হ্রাস করা; হ্রাস পাওয়া।",
    "syn": "reduce, minimise, lessen, abate",
    "ant": "enlarge, intensify, appreciate",
    "exam": "",
    "done": false
  },
  {
    "id": 49,
    "level": "Level 1",
    "word": "DURABLE",
    "pron": "ডিউরেব্‌ল",
    "meaning": "টেকসই; স্থায়ী।",
    "syn": "lasting, resistant, sustainable",
    "ant": "fragile, breakable, flimsy",
    "exam": "",
    "done": false
  },
  {
    "id": 50,
    "level": "Level 1",
    "word": "DIFFER",
    "pron": "ডিফার",
    "meaning": "বিভিন্ন হওয়া।",
    "syn": "vary, diverge",
    "ant": "conform, standardize",
    "exam": "HSC: 2019",
    "done": false
  },
  {
    "id": 51,
    "level": "Level 1",
    "word": "ENDANGER",
    "pron": "এনডেইনজার",
    "meaning": "বিপদগ্রস্থ করা; বিপন্ন করা।",
    "syn": "hazard, imperil, jeopardize",
    "ant": "protect, defend, shield, safeguard",
    "exam": "",
    "done": false
  },
  {
    "id": 52,
    "level": "Level 1",
    "word": "ENDURANCE",
    "pron": "এনডিউর‍্যানস",
    "meaning": "সহিষ্ণুতা; ধৈর্য।",
    "syn": "stamina, durability, tolerance, continuity",
    "ant": "frailty, weakness, shaky, intolerance, vulnerability",
    "exam": "",
    "done": false
  },
  {
    "id": 53,
    "level": "Level 1",
    "word": "ENHANCE",
    "pron": "এনহ্যান্স",
    "meaning": "উন্নত করা; বৃদ্ধি করা।",
    "syn": "heighten, raise, accrue",
    "ant": "diminish, shrink, reduce, lessen, depreciate",
    "exam": "",
    "done": false
  },
  {
    "id": 54,
    "level": "Level 1",
    "word": "ENTHUSIASM",
    "pron": "এনথিউছিয়্যাযিম্",
    "meaning": "প্রবল আগ্রহ।",
    "syn": "eagerness, vigor, yearn, ardor, ardent, mania",
    "ant": "apathy, indifference, languor, unconcerned, passivity",
    "exam": "প্রবাসী কল্যাণ: 2019",
    "done": false
  },
  {
    "id": 55,
    "level": "Level 1",
    "word": "ESSENTIAL",
    "pron": "এসেনশিয়াল্",
    "meaning": "অপরিহার্য।",
    "syn": "crucial, necessary, indispensable, prerequisite, compulsory, mandatory",
    "ant": "insignificant, extraneous, accessory",
    "exam": "",
    "done": false
  },
  {
    "id": 56,
    "level": "Level 1",
    "word": "ETERNAL",
    "pron": "য়েটারন্যাল্",
    "meaning": "চিরস্থায়ী।",
    "syn": "endless, everlasting, perpetual",
    "ant": "temporary, ephemeral",
    "exam": "",
    "done": false
  },
  {
    "id": 57,
    "level": "Level 1",
    "word": "EXCESS",
    "pron": "এক্সেস্",
    "meaning": "অতিরিক্ত; বাড়তি।",
    "syn": "surplus, excessive, surfeit, plethora, overabundance",
    "ant": "inadequate, shortage, scarce, paucity, exiguous",
    "exam": "",
    "done": false
  },
  {
    "id": 58,
    "level": "Level 1",
    "word": "EXPLOIT",
    "pron": "এক্সপ্লয়েট",
    "meaning": "(বীরত্বপূর্ণ) কর্ম; কৃতিত্ব।",
    "syn": "achievement, feat, adventure, heroic act, accomplishment, performance, parade",
    "ant": "failure, defeat, crush, nonfulfilment, debacle",
    "exam": "",
    "done": false
  },
  {
    "id": 59,
    "level": "Level 1",
    "word": "EXPOSE",
    "pron": "এক্সপোজ",
    "meaning": "প্রকাশ করা।",
    "syn": "reveal, disclose, debunk, show up",
    "ant": "hide, conceal, clothe, cover",
    "exam": "",
    "done": false
  },
  {
    "id": 60,
    "level": "Level 1",
    "word": "FAMILIAR",
    "pron": "ফ্যামিলিয়ার",
    "meaning": "সুপরিচিত; প্রচলিত।",
    "syn": "closely acquainted, well-known, commonplace",
    "ant": "unknown, distant, rare",
    "exam": "",
    "done": false
  },
  {
    "id": 61,
    "level": "Level 1",
    "word": "FASCINATE",
    "pron": "ফ্যাসিনেইট",
    "meaning": "মুগ্ধ / মোহিত করা।",
    "syn": "captivate, magnetize, mesmerize",
    "ant": "bore, boring, dull, stodgy, monotonous, pedestrian",
    "exam": "",
    "done": false
  },
  {
    "id": 62,
    "level": "Level 1",
    "word": "FERTILE",
    "pron": "ফারটাইল",
    "meaning": "উর্বর; ফলপ্রসূ; উদ্ভাবন শক্তি সম্পন্ন।",
    "syn": "productive, fruitful, innovative, inventive, creative",
    "ant": "infertile, sterile, barren, uninventive",
    "exam": "",
    "done": false
  },
  {
    "id": 63,
    "level": "Level 1",
    "word": "FLATTER",
    "pron": "ফ্ল্যাটার",
    "meaning": "তোষামোদ করা।",
    "syn": "over-praise, toady, adulate, cajole, inveigle",
    "ant": "censure, rebuke, chide, bad-mouth",
    "exam": "",
    "done": false
  },
  {
    "id": 64,
    "level": "Level 1",
    "word": "FLEXIBLE",
    "pron": "ফ্রেক্সিবল",
    "meaning": "নমনীয়।",
    "syn": "elastic, supple, malleable, pliable",
    "ant": "stiff, rigid, stable, unyielding",
    "exam": "37 BCS",
    "done": false
  },
  {
    "id": 65,
    "level": "Level 1",
    "word": "FUTILE",
    "pron": "ফিউটাইল",
    "meaning": "অকার্যকর; ব্যর্থ।",
    "syn": "ineffective, vain, abortive, inefficacious",
    "ant": "effective, successful, effectual",
    "exam": "",
    "done": false
  },
  {
    "id": 66,
    "level": "Level 1",
    "word": "GENUINE",
    "pron": "জেনিউইন",
    "meaning": "অকৃত্রিম; খাঁটি; আসল।",
    "syn": "authentic, honest, bonafide, real, unhypocritical",
    "ant": "counterfeit, fake, bogus, inaccurate, erroneous",
    "exam": "নির্বাচন কমিশন: 2019",
    "done": false
  },
  {
    "id": 67,
    "level": "Level 1",
    "word": "GLAMOROUS",
    "pron": "গ্ল্যামারাস্",
    "meaning": "মোহনীয়; আকর্ষণীয়।",
    "syn": "fascinating, alluring, arresting",
    "ant": "unattractive, dull, ugly",
    "exam": "37th BCS Preli",
    "done": false
  },
  {
    "id": 68,
    "level": "Level 1",
    "word": "GLOOM",
    "pron": "গ্লুম",
    "meaning": "অন্ধকার; বিষণ্ণতা।",
    "syn": "darkness, sadness, melancholy, depression",
    "ant": "light, brightness, cheerfulness, joy, happiness, optimism",
    "exam": "BAPEX: 16",
    "done": false
  },
  {
    "id": 69,
    "level": "Level 1",
    "word": "GREEDY",
    "pron": "গ্রীডি",
    "meaning": "লোভী।",
    "syn": "money-grubber, voracious, avaricious, covetous",
    "ant": "munificent, benevolent, abstemious, generous",
    "exam": "রূপালী ব্যাংক: 2019",
    "done": false
  },
  {
    "id": 70,
    "level": "Level 1",
    "word": "HAPHAZARD",
    "pron": "হ্যাপহ্যাযারড্",
    "meaning": "এলোমেলো; বিশৃঙ্খল।",
    "syn": "unmethodical, chaotic, scattered, random, incoherent",
    "ant": "organized, planned, pre-meditated, precise, systematic",
    "exam": "যবি. প্রবি.: 2020",
    "done": false
  },
  {
    "id": 71,
    "level": "Level 1",
    "word": "HARMONY",
    "pron": "হারমনি",
    "meaning": "(মতের) মিল; সঙ্গতি।",
    "syn": "agreement, compatibility",
    "ant": "disagreement, disharmony, conflict",
    "exam": "পররাষ্ট্র মন্ত্র.: 2019; ১৪তম শি.নি. (স্কুল: )17",
    "done": false
  },
  {
    "id": 72,
    "level": "Level 1",
    "word": "HAZARD",
    "pron": "হ্যাযারড্",
    "meaning": "বিপদ।",
    "syn": "danger, risk, peril, pitfall",
    "ant": "protection, safety, safeguard",
    "exam": "JU: 15; 36th BCS",
    "done": false
  },
  {
    "id": 73,
    "level": "Level 1",
    "word": "HEALTHFUL",
    "pron": "হেলথফুল",
    "meaning": "স্বাস্থ্যকর।",
    "syn": "healthy, wholesome",
    "ant": "unhealthy, morbid",
    "exam": "বশেমুরপ্রবি: 2020",
    "done": false
  },
  {
    "id": 74,
    "level": "Level 1",
    "word": "HOMOGENEOUS",
    "pron": "হোমোজেনাস্",
    "meaning": "সমশ্রেণীভূক্ত; সমপ্রকৃতি।",
    "syn": "uniform, similar, identical, compatible",
    "ant": "heterogeneous, dissimilar, different, diversity, variety",
    "exam": "RU: 15; চাবি, ৭ কলেজ: 20; ১৫তম নিবন্ধন",
    "done": false
  },
  {
    "id": 75,
    "level": "Level 1",
    "word": "HONORARY",
    "pron": "অনারারি",
    "meaning": "অবৈতনিক; বিনা বেতনে।",
    "syn": "voluntary, unpaid, titular, ostensible",
    "ant": "salaried, paid, actual",
    "exam": "মা.সহ.শি.: 2019-20",
    "done": false
  },
  {
    "id": 76,
    "level": "Level 1",
    "word": "HUMANE",
    "pron": "হিউমেইন",
    "meaning": "দয়ালু।",
    "syn": "benevolent, sympathetic",
    "ant": "ruthless, cruel, brutal",
    "exam": "MBA: 15; যশোর প্রযুক্তি বিশ্ববিদ্যালয়: 2017",
    "done": false
  },
  {
    "id": 77,
    "level": "Level 1",
    "word": "HUMBLE",
    "pron": "হাম্বল্",
    "meaning": "নম্র; নিরহঙ্কার।",
    "syn": "modest, meek, unassuming, gracious",
    "ant": "proud, egoist, boastful, arrogant",
    "exam": "Non cadre: 2019",
    "done": false
  },
  {
    "id": 78,
    "level": "Level 1",
    "word": "HUMOROUS",
    "pron": "হিউমারাস্",
    "meaning": "কৌতুকপূর্ণ।",
    "syn": "funny, amusing, playful, comic, ridiculous, laughable",
    "ant": "grave, serious",
    "exam": "JU: 19",
    "done": false
  },
  {
    "id": 79,
    "level": "Level 1",
    "word": "HYPOCRISY",
    "pron": "হি-প-ক্রিসি",
    "meaning": "ভণ্ডামী; কপটতা।",
    "syn": "insincerity, sanctimony, cant",
    "ant": "candor, sincerity, impartiality, honesty, virtue",
    "exam": "DU, C: 18-19; RU: 2014; HSC: 2019",
    "done": false
  },
  {
    "id": 80,
    "level": "Level 1",
    "word": "IGNITE",
    "pron": "ইগনাইট",
    "meaning": "জ্বলতে শুরু করা; তীব্র আবেগ জাগিয়ে তোলা।",
    "syn": "kindle, instigate, incite, agitate",
    "ant": "dampen, extinguish",
    "exam": "Combined 5 Banks-2018; RU: 19; BBS: 2019",
    "done": false
  },
  {
    "id": 81,
    "level": "Level 1",
    "word": "IGNORANT",
    "pron": "ইগ্‌নোর‍্যান্ট",
    "meaning": "অশিক্ষিত; মূর্খ; অসচেতন।",
    "syn": "uneducated, illiterate, unaware, uninformed, stupid",
    "ant": "literate, aware, wise, cognizant, smart, cunning",
    "exam": "MBBS: 2019",
    "done": false
  },
  {
    "id": 82,
    "level": "Level 1",
    "word": "ILLICIT",
    "pron": "ইলিসিট",
    "meaning": "অবৈধ; নিষিদ্ধ।",
    "syn": "unlawful, illegal, forbidden, prohibited",
    "ant": "licit, legal, legitimate",
    "exam": "JU: 14",
    "done": false
  },
  {
    "id": 83,
    "level": "Level 1",
    "word": "IMMENSE",
    "pron": "ইমেন্স",
    "meaning": "বিশাল; প্রকান্ড।",
    "syn": "enormous, gargantuan, vast, massive, tremendous",
    "ant": "tiny, minute, miniature, small",
    "exam": "পায়রা বন্দর: 2019; সাউথইস্ট B: 2016; ইসলামী B: 16",
    "done": false
  },
  {
    "id": 84,
    "level": "Level 1",
    "word": "INCREDIBLE",
    "pron": "ইনক্রেডিব্‌ল্",
    "meaning": "অবিশ্বাস্য।",
    "syn": "unbelievable, inconceivable, improbable, implausible, unlikely, absurd, preposterous",
    "ant": "plausible, credible, convincing, usual, believable",
    "exam": "IFIC 2018; DU, C: 19-20; বাংলাদেশ ব্যাংক: 16; BKB: 15",
    "done": false
  },
  {
    "id": 85,
    "level": "Level 1",
    "word": "INDIFFERENT",
    "pron": "ইন্ডিফারেন্ট",
    "meaning": "উদাসীন।",
    "syn": "apathetic, disinterested, callous",
    "ant": "enthusiastic, concerned, sympathetic, passionate",
    "exam": "IBA-BBA: 18; MBA: 16; MBM: 16; UCBL ব্যাংক: 16",
    "done": false
  },
  {
    "id": 86,
    "level": "Level 1",
    "word": "INEPT",
    "pron": "ইনপ্ট",
    "meaning": "অদক্ষ; অনুপযুক্ত।",
    "syn": "unskilled, callow, immature, unsuitable",
    "ant": "skillful, appropriate",
    "exam": "37 BCS",
    "done": false
  },
  {
    "id": 87,
    "level": "Level 1",
    "word": "INEVITABLE",
    "pron": "ইনেভিট্যাবল্",
    "meaning": "অনিবার্য; অবশ্যম্ভাবী।",
    "syn": "inescapable, ineluctable, preordained",
    "ant": "preventable, avoidable, unnecessary",
    "exam": "",
    "done": false
  },
  {
    "id": 88,
    "level": "Level 1",
    "word": "INFAMOUS",
    "pron": "ইনফেইমাস্",
    "meaning": "কুখ্যাত; জঘন্য।",
    "syn": "notorious, disreputable",
    "ant": "glorious, reputable, respectable, honorable",
    "exam": "NSI: 2019; মা.সহ.শি.: 2019-20",
    "done": false
  },
  {
    "id": 89,
    "level": "Level 1",
    "word": "INJURIOUS",
    "pron": "ইন্‌জুরিয়াস্",
    "meaning": "ক্ষতিকর।",
    "syn": "damaging, harmful, corrosive",
    "ant": "beneficial, helpful",
    "exam": "",
    "done": false
  },
  {
    "id": 90,
    "level": "Level 1",
    "word": "INTENSE",
    "pron": "ইনটেন্স",
    "meaning": "(তাপ/ অনুভূতি) তীব্র; প্রবল; (ব্যক্তি) উগ্র।",
    "syn": "extreme, acute, powerful, keen, serious, ardent, emotional, grim",
    "ant": "light, dull, mild, moderate, dispassionate, cold",
    "exam": "কম্বাইন্ড ৮, ৬ ব্যাংক: 2019; পায়রা বন্দর: 2019; MBA: 15",
    "done": false
  },
  {
    "id": 91,
    "level": "Level 1",
    "word": "INTENSIFY",
    "pron": "ইন্টেফিাই",
    "meaning": "তীব্রতা বৃদ্ধি করা।",
    "syn": "increase, boost, heighten",
    "ant": "diminish, depreciate, abate, lessen",
    "exam": "RU: 15",
    "done": false
  },
  {
    "id": 92,
    "level": "Level 1",
    "word": "IRREGULAR",
    "pron": "ইরেগ্যুলার",
    "meaning": "নিয়মবহির্ভূত; অসম।",
    "syn": "unconventional, atypical, unorthodox, deviant",
    "ant": "usual, normal, customary, uniform, stereotype, orthodox",
    "exam": "প্রবাসী কল্যাণ: 19",
    "done": false
  },
  {
    "id": 93,
    "level": "Level 1",
    "word": "IRRELEVANT",
    "pron": "ইরেলেভ্যান্ট",
    "meaning": "অপ্রাসঙ্গিক।",
    "syn": "unrelated, inconsistent, incongruent, impertinent, irrational",
    "ant": "pertinent, germane, rational, relevant",
    "exam": "পাবনা প্রযুক্তি বি. 2017",
    "done": false
  },
  {
    "id": 94,
    "level": "Level 1",
    "word": "INTELLIGENT",
    "pron": "ইনটেলিজানন্ট",
    "meaning": "বিচক্ষণ; চতুর; বুদ্ধিমান।",
    "syn": "astute, sagacious, judicious, rational, ingenious",
    "ant": "obtuse, idiotic, imbecile",
    "exam": "Combined 2 ব্যাংক: 2019; তথ্য মন্ত্রণালয়: 19; নির্বাচন কমিশন: 2019",
    "done": false
  },
  {
    "id": 95,
    "level": "Level 1",
    "word": "LATENT",
    "pron": "লেইটনট",
    "meaning": "লুক্কায়িত।",
    "syn": "dormant, lurking",
    "ant": "active, dynamic",
    "exam": "Combined 2 Banks-2018; স্বরাষ্ট্র মন্ত্রণালয়: 2019",
    "done": false
  },
  {
    "id": 96,
    "level": "Level 1",
    "word": "LAZY",
    "pron": "লেইযি",
    "meaning": "শ্রমবিমুখ; অলস।",
    "syn": "sluggish, torpid, idle, indolent, inactive",
    "ant": "energetic, animated, assiduous, industrious",
    "exam": "ইবি: 2020",
    "done": false
  },
  {
    "id": 97,
    "level": "Level 1",
    "word": "LIABILITY",
    "pron": "লাইয়্যাবিলিটি",
    "meaning": "দায়।",
    "syn": "responsibility, accountability",
    "ant": "unaccountability",
    "exam": "30th BCS; প্রা.সহ.শি. নিয়োগ: 18",
    "done": false
  },
  {
    "id": 98,
    "level": "Level 1",
    "word": "LOYALTY",
    "pron": "লয়‍্যাল্টি",
    "meaning": "বিশ্বস্ততা।",
    "syn": "fidelity, constancy, trustworthiness",
    "ant": "disloyalty, faithlessness, falseness, breach, treachery, perfidy",
    "exam": "ব্যাংক এশিয়া: 15; সাউথইস্ট ব্যাংক: 16; CU: 2019",
    "done": false
  },
  {
    "id": 99,
    "level": "Level 1",
    "word": "MAGNIFY",
    "pron": "ম্যাগনিফাই",
    "meaning": "বড় করে দেখানো; প্রশংসা করা।",
    "syn": "enlarge, praise, laud",
    "ant": "diminish, reduce, belittle",
    "exam": "নদী রক্ষা কমিশন: 19",
    "done": false
  },
  {
    "id": 100,
    "level": "Level 1",
    "word": "MASSIVE",
    "pron": "ম্যাসিভ্",
    "meaning": "বৃহদায়তন; প্রকান্ড।",
    "syn": "colossal, gigantic, astronomical, bumper, vast, gargantuan",
    "ant": "microscopic, minute, diminutive",
    "exam": "মাভাবিপ্রবি: 19-20",
    "done": false
  }
];
