[
  {
    "id": 1,
    "level": "Level 1",
    [span_0](start_span)"word": "ABANDON[span_0](end_span)",
    [span_1](start_span)"pron": "অ্যাব্যান্ডান[span_1](end_span)",
    [span_2](start_span)"meaning": "পরিত্যাগ করা।[span_2](end_span)",
    [span_3](start_span)[span_4](start_span)"syn": "desert, relinquish, abdicate, discard, give up, forsake, quit, reject, renounce, shun[span_3](end_span)[span_4](end_span)",
    [span_5](start_span)"ant": "retain, embrace, adopt, espouse, continue, pursue, uphold[span_5](end_span)",
    "exam": "EMBA Oct, 2012; RU 2009; [span_6](start_span)CU 2010-11[span_6](end_span)",
    "done": false
  },
  {
    "id": 2,
    "level": "Level 1",
    [span_7](start_span)"word": "ABATE[span_7](end_span)",
    [span_8](start_span)"pron": "অ্যাবেইট[span_8](end_span)",
    "meaning": "প্রশমিত হওয়া; [span_9](start_span)তীব্রতা কমে যাওয়া।[span_9](end_span)",
    [span_10](start_span)"syn": "subside, allay, decline, relieve, diminish, soothe, lessen, dwindle, reduce, decrease, mitigate[span_10](end_span)",
    [span_11](start_span)"ant": "intensify, boost, magnify, amplify, prolong, exacerbate, aggravate, exasperate[span_11](end_span)",
    [span_12](start_span)"exam": "অগ্রণী ব্যাংক: 2011[span_12](end_span)",
    "done": false
  },
  {
    "id": 3,
    "level": "Level 1",
    [span_13](start_span)"word": "ABDICATE[span_13](end_span)",
    [span_14](start_span)"pron": "এ্যাবৃডিকেইট[span_14](end_span)",
    "meaning": "(পদ / সিংহাসন) ত্যাগ করা; (দায়িত্ব / কর্তব্য) [span_15](start_span)পালন না করে পরিত্যাগ করা।[span_15](end_span)",
    [span_16](start_span)"syn": "shirk, relinquish, abandon, disclaim, disavow[span_16](end_span)",
    [span_17](start_span)"ant": "hold, seize, usurp[span_17](end_span)",
    [span_18](start_span)"exam": "EMBA: 2012[span_18](end_span)",
    "done": false
  },
  {
    "id": 4,
    "level": "Level 1",
    [span_19](start_span)"word": "ABERRATION[span_19](end_span)",
    [span_20](start_span)"pron": "অ্যাবে-রেই-শন[span_20](end_span)",
    "meaning": "(সঠিক নিয়ম / পদ্ধতি থেকে) বিচ্যুতি; (সচরাচর ঘটে না এমন) [span_21](start_span)অস্বাভাবিক ঘটনা।[span_21](end_span)",
    [span_22](start_span)"syn": "divergence, deviation, abnormal, queer, anomalous[span_22](end_span)",
    [span_23](start_span)"ant": "conformity, normal, compliance[span_23](end_span)",
    "exam": "কম্বাইন্ড ৫ ব্যাংক: 2019; প্রবাসী কল্যাণ ব্যাংক: 2019; [span_24](start_span)PSC: 99[span_24](end_span)",
    "done": false
  },
  {
    "id": 5,
    "level": "Level 1",
    [span_25](start_span)"word": "ABHOR[span_25](end_span)",
    [span_26](start_span)"pron": "আহোর্[span_26](end_span)",
    [span_27](start_span)"meaning": "তাচ্ছিল্যভরে অত্যন্ত ঘৃণা করা।[span_27](end_span)",
    [span_28](start_span)"syn": "loathe, detest, despise, hate, criticise, execrate, abominate, disdain, belittle[span_28](end_span)",
    [span_29](start_span)"ant": "desire, relish, cherish, praise, admire[span_29](end_span)",
    [span_30](start_span)"exam": "DU, C unit: 2011-12[span_30](end_span)",
    "done": false
  },
  {
    "id": 6,
    "level": "Level 1",
    [span_31](start_span)"word": "ABLE[span_31](end_span)",
    [span_32](start_span)"pron": "এইব্‌ল্[span_32](end_span)",
    [span_33](start_span)"meaning": "(১) সক্ষম, (২) দক্ষ।[span_33](end_span)",
    [span_34](start_span)"syn": "skilled, capable, competent, qualified, fit, adept, dexterous, dexterity, expert[span_34](end_span)",
    [span_35](start_span)"ant": "incapable, inept, clumsy[span_35](end_span)",
    "exam": "Rupali Bank: 2011; 10 BCS; [span_36](start_span)রাবি (ঘ) ২০০৯-১০[span_36](end_span)",
    "done": false
  },
  {
    "id": 7,
    "level": "Level 1",
    [span_37](start_span)"word": "ABOLISH[span_37](end_span)",
    [span_38](start_span)"pron": "অ্যা-ব-লিশ[span_38](end_span)",
    "meaning": "শেষ করা; বর্জন করা; [span_39](start_span)উচেছদ করা।[span_39](end_span)",
    [span_40](start_span)"syn": "terminate, annul, eliminate, exterminate, rescind, abrogate, repeal[span_40](end_span)",
    [span_41](start_span)"ant": "fabricate, forge, erect[span_41](end_span)",
    "exam": "Exim ব্যাংক: 18; [span_42](start_span)DU, C: 2008[span_42](end_span)",
    "done": false
  },
  {
    "id": 8,
    "level": "Level 1",
    [span_43](start_span)"word": "ABORTIVE[span_43](end_span)",
    [span_44](start_span)"pron": "অ্যাবোটি[span_44](end_span)",
    [span_45](start_span)"meaning": "নিষ্ফল / ব্যর্থ[span_45](end_span)",
    [span_46](start_span)"syn": "futile, vain, sterile, barren, debacle, unsuccessful[span_46](end_span)",
    [span_47](start_span)"ant": "fertile, fruitful, productive, successful[span_47](end_span)",
    [span_48](start_span)"exam": "DU, C unit: 2010-11[span_48](end_span)",
    "done": false
  },
  {
    "id": 9,
    "level": "Level 1",
    [span_49](start_span)"word": "ABRIDGE[span_49](end_span)",
    [span_50](start_span)"pron": "অ্যাব্রিজ[span_50](end_span)",
    [span_51](start_span)"meaning": "সংক্ষেপ করা[span_51](end_span)",
    [span_52](start_span)"syn": "condense, compress, shorten, abbreviate[span_52](end_span)",
    [span_53](start_span)"ant": "augment, enlarge, amplify, expand[span_53](end_span)",
    "exam": "ICB নিয়োগ পরীক্ষা, 2017; [span_54](start_span)Bank Job: 2009[span_54](end_span)",
    "done": false
  },
  {
    "id": 10,
    "level": "Level 1",
    [span_55](start_span)"word": "ABSTINENT[span_55](end_span)",
    [span_56](start_span)"pron": "অ্যাস্টিনেন্ট[span_56](end_span)",
    "meaning": "সংযমী; [span_57](start_span)কোনো খাদ্য বা পানীয় থেকে বিরত থাকা, বা কোনো কাজ পরিহার করা।[span_57](end_span)",
    [span_58](start_span)"syn": "abstentious, moderate, sober[span_58](end_span)",
    [span_59](start_span)"ant": "indulgent, permissive, intemperate, voluptuous, licentious, epicurean, sybaritical[span_59](end_span)",
    [span_60](start_span)"exam": "NTRCA - 2019[span_60](end_span)",
    "done": false
  },
  {
    "id": 11,
    "level": "Level 1",
    [span_61](start_span)"word": "ABSTRACT[span_61](end_span)",
    [span_62](start_span)"pron": "অ্যাবস্-ট্র্যাক্ট[span_62](end_span)",
    "meaning": "(১) প্রয়োগের ক্ষেত্রে বা বাস্তবে নয়, শুধু মতবাদ বা তত্ত্ব হিসেবে; (২) [span_63](start_span)বিমূর্ত = নৈর্ব্যক্তিক (৩) সারাংশ (৪) কোথাও থেকে কিছু সরানো[span_63](end_span)",
    [span_64](start_span)"syn": "conceptual, figurative, gist, withdraw, extract, elicit[span_64](end_span)",
    [span_65](start_span)"ant": "concrete, realistic, verbiage, insert[span_65](end_span)",
    [span_66](start_span)"exam": "DU: 2000-01[span_66](end_span)",
    "done": false
  },
  {
    "id": 12,
    "level": "Level 1",
    [span_67](start_span)"word": "ACCLAIM[span_67](end_span)",
    [span_68](start_span)"pron": "অ্যাক্লেইম্[span_68](end_span)",
    [span_69](start_span)"meaning": "(১) প্রশংসা করা = to praise publicly & enthusiastically (২) প্রশংসা।[span_69](end_span)",
    [span_70](start_span)"syn": "applaud, honor, applause, approval[span_70](end_span)",
    [span_71](start_span)"ant": "rebuke, denunciation, stricture, condemnation[span_71](end_span)",
    "exam": "বাংলাদেশ ব্যাংক: 18; [span_72](start_span)জনতা ব্যাংক: 2017[span_72](end_span)",
    "done": false
  },
  {
    "id": 13,
    "level": "Level 1",
    [span_73](start_span)"word": "ACCOST[span_73](end_span)",
    [span_74](start_span)"pron": "অ্যাকষ্ট[span_74](end_span)",
    [span_75](start_span)"meaning": "অপরিচিতের সঙ্গে গায়ে পড়ে আলাপ করা।[span_75](end_span)",
    [span_76](start_span)"syn": "encounter, address, confront, greet[span_76](end_span)",
    [span_77](start_span)"ant": "evade, avoid, shun, elude, withdraw[span_77](end_span)",
    [span_78](start_span)"exam": "DU, C: 1996-97[span_78](end_span)",
    "done": false
  },
  {
    "id": 14,
    "level": "Level 1",
    [span_79](start_span)"word": "ACQUIESCE[span_79](end_span)",
    [span_80](start_span)"pron": "অ্যাকুইয়েস্[span_80](end_span)",
    "meaning": "কোনো কিছু বিনা প্রতিবাদে, নীরবে মেনে নেয়া; [span_81](start_span)মৌনতার মাধ্যমে সম্মতি দেয়া।[span_81](end_span)",
    [span_82](start_span)"syn": "comply, assent, agree, accede, accept[span_82](end_span)",
    [span_83](start_span)"ant": "resist, disavow, disagree, repudiate, argue, oppose[span_83](end_span)",
    [span_84](start_span)"exam": "Pubali ব্যাংক: 2019[span_84](end_span)",
    "done": false
  },
  {
    "id": 15,
    "level": "Level 1",
    [span_85](start_span)"word": "ACUMEN[span_85](end_span)",
    [span_86](start_span)"pron": "অ্যাকিউমেন[span_86](end_span)",
    [span_87](start_span)"meaning": "তীক্ষ্ম বুদ্ধি।[span_87](end_span)",
    [span_88](start_span)"syn": "insight, shrewdness, sagacity, astuteness, perspicacity, discernment, penetration, agility[span_88](end_span)",
    [span_89](start_span)"ant": "ignorance, unawareness, shallowness[span_89](end_span)",
    [span_90](start_span)"exam": "RU: 2016-17[span_90](end_span)",
    "done": false
  },
  {
    "id": 16,
    "level": "Level 1",
    [span_91](start_span)"word": "ADAPT[span_91](end_span)",
    [span_92](start_span)"pron": "অ্যাডাপ্[span_92](end_span)",
    [span_93](start_span)"meaning": "খাপ খাওয়ানো, মানিয়ে নেয়া।[span_93](end_span)",
    [span_94](start_span)"syn": "adjust, conform, tailor, habituate, modify, accustom, suit, readjust[span_94](end_span)",
    [span_95](start_span)"ant": "misfit, clash[span_95](end_span)",
    [span_96](start_span)"exam": "উত্তরা ব্যাংক CO, 2017[span_96](end_span)",
    "done": false
  },
  {
    "id": 17,
    "level": "Level 1",
    [span_97](start_span)"word": "BARREN[span_97](end_span)",
    [span_98](start_span)"pron": "ব্যারেন[span_98](end_span)",
    [span_99](start_span)"meaning": "অনুর্বর: বন্ধ্যা: নিষ্ফল।[span_99](end_span)",
    [span_100](start_span)[span_101](start_span)"syn": "Infertile, Sterile, Unproductive, Arid, Impotent[span_100](end_span)[span_101](end_span)",
    [span_102](start_span)"ant": "Productive, Fertile, Fecund[span_102](end_span)",
    [span_103](start_span)"exam": "Level 1 Category[span_103](end_span)",
    "done": false
  },
  {
    "id": 18,
    "level": "Level 1",
    [span_104](start_span)"word": "BENEFACTOR[span_104](end_span)",
    [span_105](start_span)"pron": "বেনেফ্যাক্টর[span_105](end_span)",
    [span_106](start_span)"meaning": "উপকারক: দাতা[span_106](end_span)",
    [span_107](start_span)[span_108](start_span)"syn": "Patron, Donor, Contributor[span_107](end_span)[span_108](end_span)",
    [span_109](start_span)"ant": "Malefactor, Persecutor[span_109](end_span)",
    [span_110](start_span)"exam": "Level 1 Category[span_110](end_span)",
    "done": false
  },
  {
    "id": 19,
    "level": "Level 1",
    [span_111](start_span)"word": "BENEFICIAL[span_111](end_span)",
    [span_112](start_span)"pron": "বেনেফিশিয়াল[span_112](end_span)",
    [span_113](start_span)"meaning": "উপকারী[span_113](end_span)",
    [span_114](start_span)[span_115](start_span)"syn": "Useful, Advantageous, Benign[span_114](end_span)[span_115](end_span)",
    [span_116](start_span)"ant": "Useless, Harmful, Malignant[span_116](end_span)",
    "exam": "RU: 2016; শিপিং: 2019; [span_117](start_span)NTRCA: 2019[span_117](end_span)",
    "done": false
  },
  {
    "id": 20,
    "level": "Level 1",
    [span_118](start_span)"word": "BENEVOLENT[span_118](end_span)",
    [span_119](start_span)"pron": "বেনেভোলেন্ট[span_119](end_span)",
    [span_120](start_span)"meaning": "দয়ালু: সদাশয়[span_120](end_span)",
    [span_121](start_span)"syn": "Unselfish, Kind, Merciful[span_121](end_span)",
    [span_122](start_span)"ant": "Cruel, Selfish, Greedy, Malicious[span_122](end_span)",
    [span_123](start_span)"exam": "Level 1 Category[span_123](end_span)",
    "done": false
  }
]
[
  {
    "id": 21,
    "level": "Level 1",
    "word": "BLAME",
    "pron": "ব্লেইম্",
    "meaning": "দোষ দেয়া।",
    "syn": "criticize, censure",
    "ant": "praise, admire, commend",
    "exam": "BBA: 2017",
    "done": false
  },
  {
    "id": 22,
    "level": "Level 1",
    "word": "BLAMEWORTHY",
    "pron": "ব্লেইওয়ারদি",
    "meaning": "নিন্দনীয়; দূষণীয়।",
    "syn": "responsible, reprehensible",
    "ant": "spotless, immaculate, innocent",
    "exam": "BAPEX: 16",
    "done": false
  },
  {
    "id": 23,
    "level": "Level 1",
    "word": "BOAST",
    "pron": "বোস্ট",
    "meaning": "দম্ভ করা; অহংকার করা।",
    "syn": "show off, brag, pride",
    "ant": "modesty, humility",
    "exam": "DU, C: 2020; JU: 14",
    "done": false
  },
  {
    "id": 24,
    "level": "Level 1",
    "word": "BOUNTY",
    "pron": "বাউন্টি",
    "meaning": "পুরস্কার; উদার দানশীলতা।",
    "syn": "reward, prize, gift, generosity",
    "ant": "penalty, miserliness, avarice",
    "exam": "27th BCS; ইবি, B: 2020",
    "done": false
  },
  {
    "id": 25,
    "level": "Level 1",
    "word": "BONA-FIDE",
    "pron": "বোনা-ফাইড",
    "meaning": "খাঁটি; প্রকৃত।",
    "syn": "genuine, authentic",
    "ant": "bogus, counterfeit",
    "exam": "38th BCS",
    "done": false
  },
  {
    "id": 26,
    "level": "Level 1",
    "word": "BRIEF",
    "pron": "ব্রীফ",
    "meaning": "সংক্ষিপ্ত; ক্ষণস্থায়ী।",
    "syn": "short",
    "ant": "lengthy, verbosity, prolonged",
    "exam": "",
    "done": false
  },
  {
    "id": 27,
    "level": "Level 1",
    "word": "BRUTAL",
    "pron": "ব্রুট্যাল্",
    "meaning": "নিষ্ঠুর; পাশবিক।",
    "syn": "cruel, inhuman",
    "ant": "soft-hearted, kind, merciful",
    "exam": "",
    "done": false
  },
  {
    "id": 28,
    "level": "Level 1",
    "word": "CANDOR",
    "pron": "ক্যান্ডর",
    "meaning": "অকপটতা; সরলতা।",
    "syn": "frankness, sincerity, openness",
    "ant": "diplomacy, dishonesty, hypocrisy",
    "exam": "BRUR: 18; 14th Teacher Reg",
    "done": false
  },
  {
    "id": 29,
    "level": "Level 1",
    "word": "CAPABLE",
    "pron": "কেইপাব্‌ল",
    "meaning": "যোগ্য; সক্ষম।",
    "syn": "adept, able, adroit, expert, competent",
    "ant": "inept, unskilled, incompetent, incapable",
    "exam": "MBBS: 2019-20",
    "done": false
  },
  {
    "id": 30,
    "level": "Level 1",
    "word": "CARELESS",
    "pron": "কেয়ারলেস্",
    "meaning": "অসতর্ক।",
    "syn": "negligent, incautious, insincere",
    "ant": "prudent, attentive, aware",
    "exam": "",
    "done": false
  },
  {
    "id": 31,
    "level": "Level 1",
    "word": "CAUTIOUS",
    "pron": "কশাস্",
    "meaning": "সতর্ক; সতর্কতাপূর্ণ।",
    "syn": "circumspect, vigilant, alert, discreet",
    "ant": "rash, reckless, careless",
    "exam": "DU, D: 19-20; JU: 14",
    "done": false
  },
  {
    "id": 32,
    "level": "Level 1",
    "word": "CHAOS",
    "pron": "ক্যাওস্",
    "meaning": "বিশৃঙ্খলা।",
    "syn": "disorder, mess, anarchy",
    "ant": "order, harmony",
    "exam": "RU: 15; RU: 14",
    "done": false
  },
  {
    "id": 33,
    "level": "Level 1",
    "word": "CHARITABLE",
    "pron": "চ্যারিট্যাবল্",
    "meaning": "দানশীল; সদয়; ক্ষমাশীল।",
    "syn": "munificent, generous, liberal, humane, beneficent",
    "ant": "miserly, parsimonious, stingy, unkind, merciless",
    "exam": "BRUR: 16; KU: 2019; NTRCA: 2019",
    "done": false
  },
  {
    "id": 34,
    "level": "Level 1",
    "word": "COALESCE",
    "pron": "কোয়ালেস্",
    "meaning": "একীভূত হওয়া।",
    "syn": "unify, unite, amalgamate, merge, integrate, combine",
    "ant": "separate, divide, segment, split, segregate",
    "exam": "মধুমতি ব্যাংক: 2017",
    "done": false
  },
  {
    "id": 35,
    "level": "Level 1",
    "word": "COMPULSORY",
    "pron": "কাম্পালসরি",
    "meaning": "বাধ্যতামূলক।",
    "syn": "mandatory, obligatory, requisite",
    "ant": "voluntary, optional",
    "exam": "BSC 6 B: 2019; NSI: 19",
    "done": false
  },
  {
    "id": 36,
    "level": "Level 1",
    "word": "CONCEAL",
    "pron": "কনসীল্",
    "meaning": "লুকাইয়া রাখা; গুপ্ত রাখা।",
    "syn": "hide, cover, submerge, disguise, camouflage",
    "ant": "reveal, disclose, unearth",
    "exam": "সোনালী ব্যাংক: 2019",
    "done": false
  },
  {
    "id": 37,
    "level": "Level 1",
    "word": "CONSTRUCTIVE",
    "pron": "কনস্ট্রাকটিভ",
    "meaning": "গঠনমূলক।",
    "syn": "beneficial, wholesome, productive, conducive",
    "ant": "destructive, useless, worthless",
    "exam": "JU: 16",
    "done": false
  },
  {
    "id": 38,
    "level": "Level 1",
    "word": "CONTAMINATE",
    "pron": "কনট্যামিনেট",
    "meaning": "দূষিত করা।",
    "syn": "adulterate, pollute, spoil, muddy",
    "ant": "purify, rinse, decontaminate",
    "exam": "",
    "done": false
  },
  {
    "id": 39,
    "level": "Level 1",
    "word": "CONTRADICT",
    "pron": "কনট্র্যাডিক্ট",
    "meaning": "বিরুদ্ধে বলা; যুক্তি খণ্ডন করা।",
    "syn": "refute, dispute, contravene, negate",
    "ant": "corroborate, confirm, affirm, support",
    "exam": "মাদক অধিদপ্তর: 2019; GRE",
    "done": false
  },
  {
    "id": 40,
    "level": "Level 1",
    "word": "CONVICT",
    "pron": "কনভিক্ট",
    "meaning": "দোষী বলে রায় দেয়া।",
    "syn": "find guilty, sentence, punish, condemn",
    "ant": "acquit, exonerate, absolve, exculpate",
    "exam": "Home মিনিস্ট্রি: 2019",
    "done": false
  },
  {
    "id": 41,
    "level": "Level 1",
    "word": "COUNTERFEIT",
    "pron": "কাউনটারফীট",
    "meaning": "জাল; কৃত্রিম।",
    "syn": "fake, bogus, mendacious, pirated",
    "ant": "genuine, real, authentic",
    "exam": "কৃষি মন্ত্রণালয়: 19",
    "done": false
  },
  {
    "id": 42,
    "level": "Level 1",
    "word": "CRISIS",
    "pron": "ক্রাইসিস",
    "meaning": "সঙ্কটকাল; চরম উদ্বেগপূর্ণ পরিস্থিতি।",
    "syn": "climax, critical situation, dilemma, deadlock",
    "ant": "blessing, calm",
    "exam": "Non cadre: 2019; সোনালী ব্যাংক: 2019",
    "done": false
  },
  {
    "id": 43,
    "level": "Level 1",
    "word": "CRUEL",
    "pron": "ক্রুয়েল",
    "meaning": "নিষ্ঠুর; নৃশংস।",
    "syn": "brutal, ruthless, callous, savage",
    "ant": "benevolent, humane, kind, compassionate",
    "exam": "প্রবাসী কল্যাণ: 2018; MBM: 16",
    "done": false
  },
  {
    "id": 44,
    "level": "Level 1",
    "word": "CYNICAL",
    "pron": "সিনিকেল",
    "meaning": "নৈরাশ্যবাদীর আচরণসম্পন্ন; স্বার্থপর।",
    "syn": "pessimistic, skeptical, distrustful",
    "ant": "optimistic, trustful, cheerful",
    "exam": "32nd BCS Preli",
    "done": false
  },
  {
    "id": 45,
    "level": "Level 1",
    "word": "DELIBERATE",
    "pron": "ডেলিবারেট",
    "meaning": "সুচিন্তিত; স্বোচ্ছাকৃত।",
    "syn": "preplanned, calculated",
    "ant": "rash, hurried, unconscious",
    "exam": "প্রা.সহ.শি. নিয়োগ: 18; BWDB: 2019",
    "done": false
  },
  {
    "id": 46,
    "level": "Level 1",
    "word": "DENY",
    "pron": "ডিনাই",
    "meaning": "অস্বীকার করা।",
    "syn": "refute, gainsay, renounce",
    "ant": "confirm, affirm, concede",
    "exam": "NSI: 2019",
    "done": false
  },
  {
    "id": 47,
    "level": "Level 1",
    "word": "DETER",
    "pron": "ডিটার",
    "meaning": "নিবৃত্ত করা; বাধা দেয়া।",
    "syn": "obstruct, discourage, prohibit, prevent",
    "ant": "assist, aid, persuade, encourage",
    "exam": "BBS: 2020",
    "done": false
  },
  {
    "id": 48,
    "level": "Level 1",
    "word": "DIMINISH",
    "pron": "ডিমিনিশ্",
    "meaning": "হ্রাস করা; হ্রাস পাওয়া।",
    "syn": "reduce, minimise, lessen, abate",
    "ant": "enlarge, intensify, appreciate",
    "exam": "",
    "done": false
  },
  {
    "id": 49,
    "level": "Level 1",
    "word": "DURABLE",
    "pron": "ডিউরেব্‌ল",
    "meaning": "টেকসই; স্থায়ী।",
    "syn": "lasting, resistant, sustainable",
    "ant": "fragile, breakable, flimsy",
    "exam": "",
    "done": false
  },
  {
    "id": 50,
    "level": "Level 1",
    "word": "DIFFER",
    "pron": "ডিফার",
    "meaning": "বিভিন্ন হওয়া।",
    "syn": "vary, diverge",
    "ant": "conform, standardize",
    "exam": "HSC: 2019",
    "done": false
  }
]
